{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(up,job)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"fastapi-services\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (\r\n  rate(http_request_duration_seconds_sum{job=\"$app_name\", handler!=\"/metrics\"}[1m])\r\n)\r\n/\r\nsum by (handler) (\r\n  rate(http_request_duration_seconds_count{job=\"$app_name\", handler!=\"/metrics\"}[1m])\r\n)\r\n",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$app_name\"}[1m])\r\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (\r\n  rate(http_requests_total{job=\"$app_name\", status=~\"2..\", handler!=\"/metrics\"}[5m])\r\n)\r\n/\r\nsum by(handler) (\r\n  rate(http_requests_total{job=\"$app_name\", handler!=\"/metrics\"}[5m])\r\n)\r\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{status=\"500\"}[5m])"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (\r\n  rate(http_requests_total{job=\"$app_name\", status=~\"5..\", handler!=\"/metrics\"}[5m])\r\n)\r\n/\r\nsum by(handler) (\r\n  rate(http_requests_total{job=\"$app_name\", handler!=\"/metrics\"}[5m])\r\n)\r\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum(rate(http_request_duration_seconds_bucket{job=\"$app_name\", handler!=\"/metrics\"}[1m])) by (handler, le)\r\n)\r\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "topk(5, rate(http_requests_total{job=\"fastapi-services\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(level) (rate({container=\"online-shop-shop-1\"} [5m]))"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{container=\"online-shop-shop-1\"} |~ `ERROR|Exception`"
    }
   ]
  }
 ]
}