global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi-services"
    metrics_path: "/metrics"
    static_configs:
      - targets: [
          "shop:8000",
        ]

  - job_name: review-analyser
    static_configs:
      - targets: [ "review-analyser:8000" ]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:7071", "kafka-connect:7071"]