global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi-services"
    metrics_path: "/metrics"
    static_configs:
      - targets: [
          "product-service:8000",
          "review-service:8010",
          "activity-collector:8020"
        ]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:7071", "kafka-connect:7071"]

  - job_name: "flink"
    static_configs:
      - targets: ["flink-job:9249"]